version: '3.7'

services:
    postgres:
        container_name: postgres
        image: postgis/postgis:latest
        ports:
            - 127.0.0.1:5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=gwizd

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
            - 127.0.0.1:8080:80
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        environment:
            - PGADMIN_LISTEN_ADDRESS=0.0.0.0
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        depends_on:
            - postgres

volumes:
    postgres-data:
        driver: local
    pgadmin-data:
        driver: local
